[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ballsdex-art"
version = "0.0.0"

description = "Approve, selct and view bd art"
license = "MIT"
authors = [
    { name = "Haymooed" },
]
readme = "README.md"

dependencies = [

]
